-- 관리자계정에서 계정 생성 [ TEST0504_ncsUser ]
-- CREATE USER ncsUser IDENTIFIED BY ncsUser;
-- GRANT CONNECT, RESOURCE TO ncsUser;

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(30) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(100) NOT NULL,
    MEMBER_NM VARCHAR2(15) NOT NULL,
    MEMBER_ENROLL_DT DATE DEFAULT SYSDATE
);

INSERT INTO MEMBER VALUES('user01', 'pass01', '홍길동', DEFAULT);

COMMIT;

